version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    command: npm start
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - LetsTalk
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
    - "8080:8080"
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    networks:
    - LetsTalk
    
networks:
  LetsTalk:
    driver: bridge